package dev.bee.beecode.android

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts a secret with a key held in the Android Keystore.
 *
 * The WebDAV password was stored as plaintext in the profile database, and every place that
 * mentioned it said so. The reasoning was defensible — the same database already holds every
 * solution the learner has written, so a reader who can open it already has the thing worth
 * protecting — but it left a credential recoverable from a stolen device backup or an adb
 * pull, which the solutions are not: a password unlocks a *remote* account.
 *
 * So this closes it on the platform that can. The key lives in the Android Keystore, which
 * on most modern devices means hardware-backed: the key material never enters app memory
 * and cannot be extracted by reading files, only used by this app on this device. A backup
 * copied elsewhere decrypts to nothing.
 *
 * ### Why AES/GCM, and why no new dependency
 *
 * `AndroidKeyStore` with AES/GCM has been available since API 23 and minSdk is 26, so this
 * needs nothing added. `EncryptedSharedPreferences` from androidx.security would be less
 * code but it is a different storage location, and moving the credential out of the profile
 * database would mean two places to remember when a profile is deleted.
 *
 * GCM is authenticated encryption, so a tampered ciphertext fails to decrypt rather than
 * returning plausible garbage that would be sent to a server as a password.
 *
 * ### What happens when decryption fails
 *
 * [decrypt] returns null rather than throwing, and that case is *expected* rather than
 * exceptional: the key is destroyed when the app is uninstalled, when a device is factory
 * reset, and — on some devices — when the screen lock is removed. A learner in that
 * situation needs to be asked for their password again, not shown a crash.
 *
 * ### What this does not solve
 *
 * The desktop client has no equivalent. There is no cross-platform keystore that is not
 * either a large dependency or a fake, and a JVM keystore protected by a password stored
 * next to it protects nothing. So desktop still stores the credential in the clear, its UI
 * still says so, and the difference between the platforms is now real rather than uniform
 * pessimism.
 */
object KeystoreSecretStore {

    /**
     * Encrypt [plaintext] for storage, or return null if the platform refuses.
     *
     * Null means "keep behaving as before": the caller stores the plaintext, because a
     * learner whose device cannot provide a keystore should still be able to sync rather
     * than being locked out of a feature by a hardening measure.
     */
    fun encrypt(plaintext: String): String? = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val ciphertext = cipher.doFinal(plaintext.encodeToByteArray())
        // The IV is generated by the cipher and must be kept: GCM cannot decrypt without it,
        // and reusing one across encryptions with the same key is a real break. Prefixed
        // rather than stored separately so the two can never be separated.
        val encoder = Base64.getEncoder()
        PREFIX + encoder.encodeToString(cipher.iv) + SEPARATOR + encoder.encodeToString(ciphertext)
    }.getOrNull()

    /**
     * Decrypt a value produced by [encrypt].
     *
     * A value without [PREFIX] is returned unchanged: that is a plaintext credential stored
     * before this existed, or on a device where encryption was unavailable. Migrating it
     * silently on the next read is what makes this a fix for existing installs rather than
     * only for new ones — see [isEncrypted].
     */
    fun decrypt(stored: String): String? {
        if (!stored.startsWith(PREFIX)) return stored
        return runCatching {
            val body = stored.removePrefix(PREFIX)
            val separator = body.indexOf(SEPARATOR)
            if (separator <= 0) return null
            val decoder = Base64.getDecoder()
            val iv = decoder.decode(body.substring(0, separator))
            val ciphertext = decoder.decode(body.substring(separator + 1))
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
            cipher.doFinal(ciphertext).decodeToString()
        }.getOrNull()
    }

    /** Whether a stored value is already encrypted, so a caller can migrate one that is not. */
    fun isEncrypted(stored: String): Boolean = stored.startsWith(PREFIX)

    /**
     * The app's own key, created on first use.
     *
     * `setUserAuthenticationRequired` is deliberately **not** set. It would require the
     * learner to unlock the device for every sync, which for a background-capable feature
     * means sync silently failing whenever the phone is locked — worse than the threat it
     * addresses here, since the attacker this defends against has the *files*, not an
     * unlocked device in their hand.
     */
    private fun key(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    /**
     * Marks a value as encrypted by this class.
     *
     * A prefix rather than a separate column, so an existing plaintext credential is
     * recognizable without a schema change and a migration cannot half-run.
     */
    internal const val PREFIX = "beecode-aesgcm-v1:"
    private const val SEPARATOR = '.'
    private const val PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS = "beecode-sync-credential"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val TAG_BITS = 128
    private const val KEY_BITS = 256
}
